listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0      # <- 绑定所有网卡
external-ip=YOUR_SERVER_IP

realm=livekit.local
fingerprint
lt-cred-mech
user=livekit:EmeoBbU1mv75J0hO5

min-port=50000
max-port=60000

verbose
simple-log
