org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.enableDexingArtifactTransform=false
kotlin.code.style=official
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=34
# org.gradle.java.home=<path-to-your-JDK-17-home>  # optional; set only if Gradle cannot auto-detect your JDK
